# coding: utf-8

"""
    Mobile Money API

    This document defines the RESTful endpoints provided by the GSMA Mobile Money API You can find out more about what the API can do for your business at [https://developer.mobilemoneyapi.io]   # noqa: E501

    OpenAPI spec version: 1.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.links_api import LinksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLinksApi(unittest.TestCase):
    """LinksApi unit test stubs"""

    def setUp(self):
        self.api = api.links_api.LinksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accounts_account_id_links_link_reference_get(self):
        """Test case for accounts_account_id_links_link_reference_get

        View A Link  # noqa: E501
        """
        pass

    def test_accounts_account_id_links_link_reference_patch(self):
        """Test case for accounts_account_id_links_link_reference_patch

        Update A Link  # noqa: E501
        """
        pass

    def test_accounts_account_id_links_post(self):
        """Test case for accounts_account_id_links_post

        Create A Link  # noqa: E501
        """
        pass

    def test_accounts_identifier_type_identifier_links_link_reference_get(self):
        """Test case for accounts_identifier_type_identifier_links_link_reference_get

        View A Link  # noqa: E501
        """
        pass

    def test_accounts_identifier_type_identifier_links_link_reference_patch(self):
        """Test case for accounts_identifier_type_identifier_links_link_reference_patch

        Update A Link  # noqa: E501
        """
        pass

    def test_accounts_identifier_type_identifier_links_post(self):
        """Test case for accounts_identifier_type_identifier_links_post

        Create A Link  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
