# coding: utf-8

"""
    Mobile Money API

    This document defines the RESTful endpoints provided by the GSMA Mobile Money API You can find out more about what the API can do for your business at [https://developer.mobilemoneyapi.io]   # noqa: E501

    OpenAPI spec version: 1.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.code_lifetime import CodeLifetime  # noqa: E501
from swagger_client.rest import ApiException


class TestCodeLifetime(unittest.TestCase):
    """CodeLifetime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodeLifetime(self):
        """Test CodeLifetime"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.code_lifetime.CodeLifetime()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
