# coding: utf-8

"""
    Mobile Money API

    This document defines the RESTful endpoints provided by the GSMA Mobile Money API You can find out more about what the API can do for your business at [https://developer.mobilemoneyapi.io]   # noqa: E501

    OpenAPI spec version: 1.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.supporting_api import SupportingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSupportingApi(unittest.TestCase):
    """SupportingApi unit test stubs"""

    def setUp(self):
        self.api = api.supporting_api.SupportingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_heartbeat_get(self):
        """Test case for heartbeat_get

        Check API availability  # noqa: E501
        """
        pass

    def test_requeststates_server_correlation_id_get(self):
        """Test case for requeststates_server_correlation_id_get

        View A Request State  # noqa: E501
        """
        pass

    def test_requeststates_server_correlation_id_patch(self):
        """Test case for requeststates_server_correlation_id_patch

        Update A Request State  # noqa: E501
        """
        pass

    def test_responses_client_correlation_id_get(self):
        """Test case for responses_client_correlation_id_get

        View A Response  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
