# coding: utf-8

"""
    Mobile Money API

    This document defines the RESTful endpoints provided by the GSMA Mobile Money API You can find out more about what the API can do for your business at [https://developer.mobilemoneyapi.io]   # noqa: E501

    OpenAPI spec version: 1.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.authorisation_codes_api import AuthorisationCodesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthorisationCodesApi(unittest.TestCase):
    """AuthorisationCodesApi unit test stubs"""

    def setUp(self):
        self.api = api.authorisation_codes_api.AuthorisationCodesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accounts_account_id_authorisation_code_authorisation_code_get(self):
        """Test case for accounts_account_id_authorisation_code_authorisation_code_get

        View an Authorisation Code  # noqa: E501
        """
        pass

    def test_accounts_account_id_authorisation_codes_authorisation_code_patch(self):
        """Test case for accounts_account_id_authorisation_codes_authorisation_code_patch

        Update an Authorisation Code  # noqa: E501
        """
        pass

    def test_accounts_account_id_authorisationcodes_post(self):
        """Test case for accounts_account_id_authorisationcodes_post

        Create an Authorisation Code  # noqa: E501
        """
        pass

    def test_accounts_identifier_type_identifier_authorisation_codes_authorisation_code_get(self):
        """Test case for accounts_identifier_type_identifier_authorisation_codes_authorisation_code_get

        View an Authorisation Code  # noqa: E501
        """
        pass

    def test_accounts_identifier_type_identifier_authorisation_codes_authorisation_code_patch(self):
        """Test case for accounts_identifier_type_identifier_authorisation_codes_authorisation_code_patch

        Cancel an Authorisation Code  # noqa: E501
        """
        pass

    def test_accounts_identifier_type_identifier_authorisation_codes_post(self):
        """Test case for accounts_identifier_type_identifier_authorisation_codes_post

        Create an Authorisation Code via an account identifier.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
