# coding: utf-8

"""
    Mobile Money API

    This document defines the RESTful endpoints provided by the GSMA Mobile Money API You can find out more about what the API can do for your business at [https://developer.mobilemoneyapi.io]   # noqa: E501

    OpenAPI spec version: 1.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.accounts_api import AccountsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = api.accounts_api.AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accounts_account_id_accountname_get(self):
        """Test case for accounts_account_id_accountname_get

        View Account Name  # noqa: E501
        """
        pass

    def test_accounts_account_id_balance_get(self):
        """Test case for accounts_account_id_balance_get

        View Account Balance  # noqa: E501
        """
        pass

    def test_accounts_account_id_statemententries_get(self):
        """Test case for accounts_account_id_statemententries_get

        View Account Statements  # noqa: E501
        """
        pass

    def test_accounts_account_id_status_get(self):
        """Test case for accounts_account_id_status_get

        View Account Status  # noqa: E501
        """
        pass

    def test_accounts_account_id_transactions_get(self):
        """Test case for accounts_account_id_transactions_get

        View Account Specific Transaction  # noqa: E501
        """
        pass

    def test_accounts_balance_get(self):
        """Test case for accounts_balance_get

        View Account Balance  # noqa: E501
        """
        pass

    def test_accounts_identifier_type_identifier_accountname_get(self):
        """Test case for accounts_identifier_type_identifier_accountname_get

        View Account Name  # noqa: E501
        """
        pass

    def test_accounts_identifier_type_identifier_balance_get(self):
        """Test case for accounts_identifier_type_identifier_balance_get

        View Account Balance  # noqa: E501
        """
        pass

    def test_accounts_identifier_type_identifier_statemententries_get(self):
        """Test case for accounts_identifier_type_identifier_statemententries_get

        View Account Statements  # noqa: E501
        """
        pass

    def test_accounts_identifier_type_identifier_status_get(self):
        """Test case for accounts_identifier_type_identifier_status_get

        View Account Status  # noqa: E501
        """
        pass

    def test_accounts_identifier_type_identifier_transactions_get(self):
        """Test case for accounts_identifier_type_identifier_transactions_get

        View Account Specific Transaction  # noqa: E501
        """
        pass

    def test_statemententries_transaction_reference_get(self):
        """Test case for statemententries_transaction_reference_get

        View Specific Statement  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
